version: "3.8"

services:
  frontend:
    image: es-castle:5000/epicsoft_caveworld/frontend
    build:
      context: ./CWFrontend
      dockerfile: docker/prod.Dockerfile
    ports:
      - 8050:80
      - 8051:443
    restart: always
    deploy:
        resources:
            limits:
                cpus: '0.25'
                memory: 256M
        placement:
            constraints: [node.role == manager, node.labels.arc == x64]